# Generated by Django 4.2.1 on 2023-06-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countofficer',
        ),
    ]
