# Generated by Django 4.2.1 on 2023-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officer', '0004_delete_countofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='countofficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=14)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=14)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
