# Generated by Django 4.2.1 on 2023-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_countofficer_booth_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_no', models.IntegerField()),
                ('percentage', models.CharField(max_length=10)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
