# Generated by Django 4.2.1 on 2023-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_crowdupdate_delete_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countofficer',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='countofficer',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='countofficer',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
