# Generated by Django 4.2.1 on 2023-05-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
    ]
