# Generated by Django 4.2.1 on 2023-05-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20230525_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voter',
            new_name='VoterSignup',
        ),
    ]
