# Generated by Django 4.2.1 on 2023-05-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_rename_voter_votersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votersignup',
            old_name='dob',
            new_name='date',
        ),
    ]
