# Generated by Django 4.2.1 on 2023-06-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_rename_dob_votersignup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votersignup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='votersignup',
            name='username',
        ),
    ]
