# Generated by Django 4.2.1 on 2023-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_alter_votersignup_aadhar_id_alter_votersignup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='votersignup',
            name='email',
            field=models.CharField(default=166.58333333333334, max_length=20),
            preserve_default=False,
        ),
    ]
