# Generated by Django 4.2.1 on 2023-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
