# Generated by Django 4.2.1 on 2023-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_voter_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='aadhar_file',
            field=models.ImageField(default=95.19047619047619, upload_to='aadhar_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='image',
            field=models.ImageField(default=8.691304347826087, upload_to='voter_images/'),
            preserve_default=False,
        ),
    ]
