# Generated by Django 4.2.1 on 2023-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('voter_id', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=100)),
                ('aadhar_id', models.IntegerField(unique=True)),
                ('house_no', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='admin')),
            ],
        ),
    ]
