# Generated by Django 4.2.1 on 2023-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('radio', models.CharField(max_length=14)),
                ('dob', models.DateField()),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=14)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
