# Generated by Django 4.2.1 on 2023-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_officeradd'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeradd',
            name='booth_no',
            field=models.IntegerField(default=0.004252126063031516),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='booth_no',
            field=models.IntegerField(default=22.211111111111112),
            preserve_default=False,
        ),
    ]
