# Generated by Django 4.2.1 on 2023-06-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0005_result_alter_booth_booth_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
