# Generated by Django 4.2.1 on 2023-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_person_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeradd',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
