# Generated by Django 4.2.1 on 2023-07-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_remove_person_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='voter_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
