# Generated by Django 4.2.1 on 2023-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_alter_person_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeradd',
            name='email',
            field=models.CharField(max_length=25),
        ),
    ]
