# Generated by Django 4.2.1 on 2023-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0010_alter_officeradd_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('aadhar_id', models.CharField(max_length=12, unique=True)),
                ('house_no', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('image', models.ImageField(upload_to='voter_images/')),
            ],
        ),
    ]
