# Generated by Django 4.2.1 on 2023-07-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0012_voterregistration_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterregistration',
            old_name='approved',
            new_name='action',
        ),
    ]
