# Generated by Django 4.2.1 on 2023-07-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0013_rename_approved_voterregistration_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeradd',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='officeradd',
            name='pin',
        ),
    ]
