# Generated by Django 4.2.1 on 2023-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0014_remove_officeradd_dob_remove_officeradd_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
