# Generated by Django 4.2.1 on 2023-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0015_alter_person_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterregistration',
            name='aadhar_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
